# ESP32 settings

# Networking

## WiFi
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_NET_CONNECTION_MANAGER_CONNECTIVITY_WIFI_MGMT=y

## Resolve <hostname>.local via mDNS
CONFIG_MDNS_RESPONDER=y
# Allow enough DNS dispatcher poll slots for mDNS and DNS.
CONFIG_ZVFS_POLL_MAX=8

## DNS via DHCP
CONFIG_DNS_RESOLVER=y
# Retain both DHCP (IPv4) and router-advertised (IPv6) servers.
CONFIG_DNS_RESOLVER_MAX_SERVERS=2

## Stored Wi-Fi credentials
CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_CONNECT_STORED=y

## Credential storage
CONFIG_SETTINGS_NVS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# Memory

## Mbed TLS
# CONFIG_MBEDTLS_ENABLE_HEAP=y
# CONFIG_MBEDTLS_HEAP_SIZE=60000
