# Additional configuration for the complete or login-only gRPC client.
CONFIG_DYNAMIC_THREAD_STACK_SIZE=8192
CONFIG_POSIX_THREAD_THREADS_MAX=8
CONFIG_POSIX_THREAD_KEYS_MAX=16
CONFIG_MAX_PTHREAD_MUTEX_COUNT=64
CONFIG_MAX_PTHREAD_COND_COUNT=32
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=131072
CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_POSIX_NETWORKING=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.50"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.1.1"
CONFIG_NET_DHCPV4=n
CONFIG_DNS_RESOLVER=y
CONFIG_NET_SOCKETS_POLL_MAX=16
CONFIG_ZVFS_OPEN_MAX=24
CONFIG_EVENTFD=y
CONFIG_ZVFS_EVENTFD_MAX=8
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
CONFIG_LTO=y
